/**
 * DICIONÁRIO DE MÉTRICAS — uma definição por KPI, apontando para a função
 * que calcula em lib/crm/metricas.ts. Toda tela lê daqui o nome e o texto;
 * nenhuma tela redefine fórmula.
 */
export interface DefinicaoKpi {
  id: string;
  nome: string;
  definicao: string;
  formula: string;
  fonte: string;
  baseDeData: string;
  ressalvas: string;
  funcao: string;
}

export const KPIS: DefinicaoKpi[] = [
  { id: "leads", nome: "Leads", definicao: "Pessoas com interesse comercial registrado (lead criado), independentemente de virarem clientes.", formula: "count(crm_leads)", fonte: "crm_leads.created_at", baseDeData: "data de criação do lead", ressalvas: "Lead reaberto/reativado não é contado de novo; é o mesmo registro.", funcao: "—" },
  { id: "lead_para_venda", nome: "Lead → Venda (conversão total)", definicao: "Fração dos leads criados no período que viraram venda.", formula: "vendas / leads", fonte: "crm_leads, crm_opportunities.won_at", baseDeData: "coorte pela data de criação do lead", ressalvas: "Leads recentes ainda podem converter: coorte imatura aparece com aviso.", funcao: "taxasFunil" },
  { id: "show_rate", nome: "Show rate", definicao: "Aulas experimentais realizadas sobre agendadas.", formula: "realizadas / agendadas", fonte: "crm_trials.status", baseDeData: "data agendada", ressalvas: "Cancelada pelo cliente com aviso conta como agendada; no-show é ausência sem aviso.", funcao: "showRate" },
  { id: "no_show_rate", nome: "No-show rate", definicao: "Ausências sem aviso sobre agendadas.", formula: "no_shows / agendadas", fonte: "crm_trials.status", baseDeData: "data agendada", ressalvas: "", funcao: "noShowRate" },
  { id: "win_rate", nome: "Win rate", definicao: "Propostas enviadas que viraram venda.", formula: "ganhas / propostas enviadas", fonte: "crm_opportunities.proposal_sent_at, won_at", baseDeData: "data da proposta", ressalvas: "Proposta em aberto conta no denominador só quando o período fecha (coorte).", funcao: "winRate" },
  { id: "ciclo_venda", nome: "Ciclo de venda", definicao: "Dias entre lead criado e ganho. Mostrado em mediana, média e P75.", formula: "won_at − lead.created_at", fonte: "crm_leads, crm_opportunities", baseDeData: "data do ganho", ressalvas: "Média é distorcida por casos extremos; use a mediana para decidir.", funcao: "cicloDeVendaDias" },
  { id: "primeira_resposta", nome: "Tempo de primeira resposta", definicao: "Minutos entre lead criado e o primeiro contato humano registrado.", formula: "first_response_at − created_at", fonte: "crm_leads", baseDeData: "data de criação do lead", ressalvas: "Depende de registrar o contato no CRM. Lead sem resposta fica fora da mediana e é contado à parte.", funcao: "primeiraResposta" },
  { id: "sla_follow_up", nome: "SLA de follow-up", definicao: "Tarefas concluídas até o prazo sobre tarefas vencidas.", formula: "no prazo / vencidas", fonte: "crm_tasks", baseDeData: "due_at", ressalvas: "", funcao: "slaFollowUp" },
  { id: "pipeline_bruto", nome: "Pipeline bruto", definicao: "Soma do valor mensal potencial das oportunidades abertas.", formula: "Σ expected_value", fonte: "crm_opportunities (etapa aberta)", baseDeData: "hoje", ressalvas: "Oportunidade sem valor não entra e aparece na qualidade de dados.", funcao: "valorPipeline" },
  { id: "pipeline_ponderado", nome: "Pipeline ponderado", definicao: "Valor × probabilidade da etapa (configurada até haver histórico suficiente; depois, histórica).", formula: "Σ expected_value × probabilidade", fonte: "crm_opportunities, crm_stages", baseDeData: "hoje", ressalvas: "Probabilidade histórica só com 20+ passagens pela etapa.", funcao: "valorPipeline / probabilidadeHistorica" },
  { id: "pipeline_velocity", nome: "Pipeline velocity", definicao: "Receita potencial por dia que o pipeline gera.", formula: "oportunidades qualificadas × win rate × ticket médio / ciclo médio (dias)", fonte: "crm_opportunities", baseDeData: "últimos 90 dias", ressalvas: "Indicador derivado; muda muito com amostra pequena.", funcao: "pipelineVelocity" },
  { id: "receita_esperada", nome: "Receita esperada / contratada / recebida", definicao: "Três estados distintos do mesmo evento de receita.", formula: "Σ amount por status", fonte: "crm_revenue_events.status", baseDeData: "occurred_at", ressalvas: "Venda não é dinheiro recebido: só 'collected' entra em LTV realizado.", funcao: "receitaPorStatus" },
  { id: "mrr", nome: "MRR normalizado", definicao: "Receita recorrente mensal dos contratos ativos, normalizada pelo ciclo.", formula: "Σ valor do contrato / ciclo em meses", fonte: "crm_contracts", baseDeData: "data de referência", ressalvas: "Trimestral de 1.200 entra como 400. Avulso não entra. É diferente de caixa recebido.", funcao: "mrrNormalizado" },
  { id: "mrr_movimento", nome: "Novo / Expansão / Contração / Churn de MRR", definicao: "Decomposição da variação do MRR entre duas datas, por cliente.", formula: "comparação cliente a cliente", fonte: "crm_contracts", baseDeData: "duas datas", ressalvas: "", funcao: "movimentoMrr" },
  { id: "arpu", nome: "ARPU", definicao: "Receita recebida nos últimos 30 dias por cliente ativo.", formula: "receita 30d / clientes ativos", fonte: "crm_revenue_events, crm_clients", baseDeData: "últimos 30 dias", ressalvas: "", funcao: "arpuMensal" },
  { id: "ltv_realizado", nome: "LTV realizado", definicao: "Receita efetivamente recebida de um cliente desde a aquisição, líquida de reembolsos.", formula: "Σ eventos 'collected' (refund negativo)", fonte: "crm_revenue_events", baseDeData: "desde first_purchase_at", ressalvas: "Cliente novo tem LTV baixo por definição; não compare coortes de idades diferentes.", funcao: "ltvRealizado" },
  { id: "ltv_projetado", nome: "LTV projetado", definicao: "Estimativa: ARPU mensal × vida média observada dos clientes encerrados.", formula: "ARPU × vida média (meses)", fonte: "crm_clients, crm_revenue_events", baseDeData: "hoje", ressalvas: "Só aparece com 15+ clientes, 6+ meses de histórico e 5+ encerrados. Antes disso: 'dados imaturos'.", funcao: "ltvProjetado" },
  { id: "ltv_por_fonte", nome: "LTV por origem", definicao: "LTV realizado médio dos clientes agrupados pela origem de aquisição.", formula: "média(LTV realizado) por source_code", fonte: "crm_clients.source_code", baseDeData: "desde a aquisição", ressalvas: "Origem 'unknown' aparece como grupo próprio, nunca é redistribuída.", funcao: "ltvPorFonte" },
  { id: "coortes", nome: "Coortes por mês de aquisição", definicao: "Clientes agrupados pelo mês da primeira compra: receita acumulada em 30/60/90/180/365 dias e retenção M0…M12.", formula: "retido em Mn = teve receita recebida no n-ésimo mês", fonte: "crm_clients, crm_revenue_events", baseDeData: "first_purchase_at", ressalvas: "Mês que ainda não chegou é null. Coorte com menos de 5 clientes vem marcada.", funcao: "coortes" },
  { id: "churn_clientes", nome: "Churn de clientes", definicao: "Cancelados no período sobre ativos no início do período.", formula: "cancelados / ativos no início", fonte: "crm_clients", baseDeData: "período", ressalvas: "Pausa não é churn.", funcao: "churnClientes" },
  { id: "churn_receita", nome: "Churn de receita", definicao: "MRR perdido sobre MRR no início do período.", formula: "MRR perdido / MRR inicial", fonte: "crm_contracts", baseDeData: "período", ressalvas: "Um cliente de 3.000 não vale o mesmo que um de 399.", funcao: "churnReceita" },
  { id: "retencao", nome: "Retenção", definicao: "Clientes que permanecem sobre ativos no início (30/60/90/180/365 dias).", formula: "permanecem / ativos no início", fonte: "crm_clients", baseDeData: "período", ressalvas: "", funcao: "retencaoClientes" },
  { id: "tenure", nome: "Tempo médio como cliente", definicao: "Meses entre primeira compra e cancelamento (ou hoje, se ativo).", formula: "mediana e média", fonte: "crm_clients", baseDeData: "hoje", ressalvas: "Clientes ativos puxam o número para baixo (ainda estão contando).", funcao: "tenureMeses" },
  { id: "renovacao", nome: "Taxa de renovação", definicao: "Contratos renovados sobre contratos que chegaram ao fim no período.", formula: "renovados / elegíveis", fonte: "crm_contracts", baseDeData: "fim do contrato", ressalvas: "", funcao: "taxaRenovacao" },
  { id: "reativacao", nome: "Taxa de reativação", definicao: "Ex-clientes que voltaram sobre ex-clientes trabalhados.", formula: "reativados / trabalhados", fonte: "crm_clients, crm_tasks(reativacao)", baseDeData: "período", ressalvas: "", funcao: "taxaReativacao" },
  { id: "cac_midia", nome: "CAC de mídia", definicao: "Gasto de mídia rastreado dividido pelos novos clientes atribuídos àquela mídia.", formula: "gasto / novos clientes atribuídos", fonte: "crm_ad_spend, crm_clients.source_code", baseDeData: "período do gasto", ressalvas: "NÃO é CAC total. Orgânico sem custo registrado mostra 'custo não calculado', nunca zero.", funcao: "cacMidia" },
  { id: "cac_fully_loaded", nome: "CAC total (fully loaded)", definicao: "Mídia + custos diretos de vendas e marketing, por novo cliente.", formula: "(mídia + custos) / novos clientes", fonte: "crm_ad_spend + custo informado", baseDeData: "período", ressalvas: "Só aparece quando os custos são informados nas configurações.", funcao: "cacFullyLoaded" },
  { id: "cpl", nome: "CPL / CPQL / custo por experimental / custo por venda", definicao: "Gasto dividido por leads, leads qualificados, experimentais realizadas e vendas atribuídos.", formula: "gasto / n", fonte: "crm_ad_spend, crm_leads", baseDeData: "período", ressalvas: "", funcao: "custoPorLead…" },
  { id: "ltv_cac", nome: "LTV:CAC", definicao: "LTV dividido por CAC, rotulado 'observado' (LTV realizado) ou 'projetado'.", formula: "LTV / CAC", fonte: "derivado", baseDeData: "período", ressalvas: "Nunca mistura LTV projetado com CAC incompleto sem rótulo.", funcao: "ltvCac" },
  { id: "payback", nome: "CAC payback", definicao: "Meses de receita (ou de margem, se informada) para recuperar o CAC.", formula: "CAC / receita mensal por cliente", fonte: "derivado", baseDeData: "período", ressalvas: "Payback de margem só com margem de contribuição informada.", funcao: "paybackMeses" },
  { id: "roas", nome: "ROAS de receita", definicao: "Receita atribuída aos anúncios sobre gasto em anúncios.", formula: "receita atribuída / gasto", fonte: "crm_revenue_events, crm_ad_spend", baseDeData: "período", ressalvas: "Não é ROI: não considera custos.", funcao: "roasReceita" },
  { id: "referral_rate", nome: "Referral rate", definicao: "Clientes que geraram pelo menos uma indicação sobre total de clientes.", formula: "indicadores / clientes", fonte: "crm_clients.referred_by", baseDeData: "hoje", ressalvas: "", funcao: "metricasIndicacao" },
  { id: "referral_conversion", nome: "Referral conversion rate", definicao: "Leads indicados que viraram clientes.", formula: "vendas indicadas / leads indicados", fonte: "crm_leads.source_code = referral_client", baseDeData: "data do lead", ressalvas: "", funcao: "metricasIndicacao" },
  { id: "atribuicao", nome: "Atribuição (first / lead creation / last non-direct / assistida)", definicao: "Quatro leituras dos toques conhecidos de um contato; nenhuma é 'a verdade'.", formula: "ordenação temporal dos toques", fonte: "crm_attribution_touches", baseDeData: "occurred_at", ressalvas: "Direto não apaga o papel dos outros. Unknown continua unknown.", funcao: "atribuir" },
  { id: "cobertura_atribuicao", nome: "Cobertura de atribuição", definicao: "Vendas (ou receita) com origem conhecida sobre total.", formula: "conhecidas / total", fonte: "crm_clients.source_code", baseDeData: "período", ressalvas: "Meta é subir com o tempo, não chegar a 100% inventando.", funcao: "coberturaAtribuicao" },
  { id: "lead_score", nome: "Temperatura do lead", definicao: "Quente / morno / frio por regras visíveis: experimental, proposta, perguntas de preço e horário, recência.", formula: "soma de pontos explicados", fonte: "crm_activities, crm_trials", baseDeData: "hoje", ressalvas: "Nunca usa característica pessoal ou dado de saúde.", funcao: "classificarLead" },
  { id: "lead_velocity", nome: "Lead velocity rate", definicao: "Crescimento do número de leads qualificados de um mês para o anterior.", formula: "(qualificados mês / qualificados mês anterior) − 1", fonte: "crm_stage_history(qualificado)", baseDeData: "mês", ressalvas: "Com menos de 10 por mês, o número oscila demais para orientar decisão.", funcao: "anomalia" },
];

export const kpi = (id: string) => KPIS.find((k) => k.id === id);
