import { REGIAO_LABEL, confirmado, naoConfirmado, type Academia, type Estilo, type FaixaPreco, type Regiao } from "./tipos";

/**
 * Base de academias de Alphaville.
 *
 * ATENÇÃO — ESTADO DOS DADOS
 * Cada unidade abaixo existe e está confirmada: todas têm artigo próprio no
 * site, escrito e revisado pelo Montinho. O que está majoritariamente VAZIO são
 * os atributos verificáveis (horário, preço, estacionamento, convênio).
 *
 * Isso é deliberado. Horário e preço mudam, e este ambiente de build não tem
 * acesso às páginas oficiais das academias para verificar. Preencher no
 * "achismo" quebraria a única coisa que faz esta ferramenta valer algo: a
 * confiança de que o que está escrito foi conferido.
 *
 * COMO PREENCHER
 * Troque `naoConfirmado<T>()` por:
 *   confirmado(valor, confianca, fonte, "AAAA-MM-DD")
 *
 * onde `confianca` é:
 *   "oficial"    — site ou canal oficial da academia
 *   "plataforma" — listagem da Wellhub/TotalPass
 *   "montinho"   — verificado por você na unidade (fonte legítima: você atende
 *                  alunos lá dentro; registre a data da visita)
 *
 * Rode `npx tsx scripts/academias-test.ts` para ver a completude e saber se a
 * ferramenta já tem dado suficiente para ir ao ar.
 */
export const ACADEMIAS: Academia[] = [
  {
    id: "smart-fit-alphaville",
    nome: "Smart Fit Alphaville",
    artigoSlug: "smart-fit-alphaville",
    regiao: "centro-industrial-empresarial",
    tipo: "rede",
    status: "ativa",
    vinteQuatroHoras: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDomingo: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreSabado: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    fechaDiaUtil: confirmado(23, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDiaUtil: confirmado(6, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estacionamento: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    wellhub: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    totalpass: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    personalExterno: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    faixaPreco: confirmado("economico", "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estilos: confirmado(["musculacao_completa", "pesos_livres", "cardio", "aulas_coletivas", "funcional"], "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
  },
  {
    id: "bluefit-alphaville",
    nome: "Bluefit Alphaville",
    artigoSlug: "bluefit-alphaville",
    regiao: "centro-industrial-empresarial",
    tipo: "rede",
    status: "ativa",
    vinteQuatroHoras: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDomingo: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreSabado: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    fechaDiaUtil: confirmado(24, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDiaUtil: confirmado(7, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estacionamento: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    wellhub: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    totalpass: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    personalExterno: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    faixaPreco: confirmado("economico", "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estilos: confirmado(["musculacao_completa", "pesos_livres", "maquinas", "aulas_coletivas", "funcional", "cardio"], "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
  },
  {
    id: "bodytech-alphaville",
    nome: "Bodytech Iguatemi Alphaville",
    artigoSlug: "bodytech-alphaville",
    regiao: "iguatemi",
    tipo: "rede",
    status: "ativa",
    vinteQuatroHoras: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDomingo: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreSabado: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    fechaDiaUtil: confirmado(22, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDiaUtil: confirmado(6, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estacionamento: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    wellhub: confirmado(true, "plataforma", "https://wellhub.com/pt-br/search/partners/bodytech-iguatemi-alphaville/", "2026-08-26"),
    totalpass: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    personalExterno: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    faixaPreco: confirmado("premium", "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estilos: confirmado(["musculacao_completa", "pesos_livres", "maquinas", "cardio", "aulas_coletivas", "funcional", "reservada", "premium"], "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
  },
  {
    id: "bio-ritmo-alphaville",
    nome: "Bio Ritmo Alphaville",
    artigoSlug: "bio-ritmo-alphaville",
    regiao: "centro-industrial-empresarial",
    tipo: "rede",
    status: "encerrada",
    vinteQuatroHoras: naoConfirmado<boolean>(),
    abreDomingo: naoConfirmado<boolean>(),
    abreSabado: naoConfirmado<boolean>(),
    fechaDiaUtil: naoConfirmado<number>(),
    abreDiaUtil: naoConfirmado<number>(),
    estacionamento: naoConfirmado<boolean>(),
    wellhub: naoConfirmado<boolean>(),
    totalpass: naoConfirmado<boolean>(),
    personalExterno: naoConfirmado<boolean>(),
    faixaPreco: naoConfirmado<FaixaPreco>(),
    estilos: naoConfirmado<Estilo[]>(),
  },
  {
    id: "panobianco-alphaville",
    nome: "Panobianco Alphaville",
    artigoSlug: "panobianco-alphaville",
    regiao: "centro-industrial-empresarial",
    tipo: "rede",
    status: "ativa",
    vinteQuatroHoras: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDomingo: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreSabado: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    fechaDiaUtil: confirmado(0, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDiaUtil: confirmado(5, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estacionamento: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    wellhub: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    totalpass: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    personalExterno: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    faixaPreco: confirmado("economico", "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estilos: confirmado(["musculacao_completa", "pesos_livres", "maquinas", "cardio", "aulas_coletivas"], "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
  },
  {
    id: "ironberg-alphaville",
    nome: "Ironberg Alphaville",
    artigoSlug: "ironberg-alphaville",
    regiao: "centro-industrial-empresarial",
    tipo: "rede",
    status: "ativa",
    vinteQuatroHoras: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDomingo: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreSabado: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    fechaDiaUtil: naoConfirmado<number>(),
    abreDiaUtil: naoConfirmado<number>(),
    estacionamento: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    wellhub: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    totalpass: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    personalExterno: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    faixaPreco: confirmado("premium", "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estilos: confirmado(["musculacao_completa", "pesos_livres", "maquinas", "cardio", "premium"], "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
  },
  {
    id: "nitrogym-alphaville",
    nome: "NitroGym Alphaville",
    artigoSlug: "nitrogym-alphaville",
    regiao: "centro-industrial-empresarial",
    tipo: "local",
    status: "ativa",
    vinteQuatroHoras: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDomingo: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreSabado: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    fechaDiaUtil: confirmado(0, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDiaUtil: confirmado(5, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estacionamento: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    wellhub: naoConfirmado<boolean>(),
    totalpass: naoConfirmado<boolean>(),
    personalExterno: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    faixaPreco: confirmado("intermediario", "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estilos: confirmado(["musculacao_completa", "pesos_livres", "maquinas", "cardio"], "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
  },
  {
    id: "arena-18-alphaville",
    nome: "Arena 18 Alphaville",
    artigoSlug: "arena-18-alphaville",
    regiao: "centro-industrial-empresarial",
    tipo: "local",
    status: "ativa",
    vinteQuatroHoras: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDomingo: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreSabado: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    fechaDiaUtil: naoConfirmado<number>(),
    abreDiaUtil: naoConfirmado<number>(),
    estacionamento: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    wellhub: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    totalpass: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    personalExterno: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    faixaPreco: confirmado("intermediario", "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estilos: confirmado(["musculacao_completa", "pesos_livres", "maquinas", "cardio", "aulas_coletivas", "funcional", "premium", "reservada"], "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
  },
  {
    id: "scelta-alphaville",
    nome: "Scelta Alphaville",
    artigoSlug: "scelta-alphaville",
    regiao: "centro-comercial",
    tipo: "local",
    status: "ativa",
    vinteQuatroHoras: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDomingo: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreSabado: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    fechaDiaUtil: confirmado(23, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDiaUtil: confirmado(5, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estacionamento: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    wellhub: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    totalpass: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    personalExterno: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    faixaPreco: confirmado("premium", "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estilos: confirmado(["musculacao_completa", "pesos_livres", "maquinas", "cardio", "aulas_coletivas", "funcional", "premium", "reservada"], "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
  },
  {
    id: "4perform-alphaville",
    nome: "4Perform Alphaville",
    artigoSlug: "4perform-alphaville",
    regiao: "centro-industrial-empresarial",
    tipo: "local",
    status: "ativa",
    vinteQuatroHoras: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDomingo: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreSabado: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    fechaDiaUtil: confirmado(21, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDiaUtil: confirmado(6, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estacionamento: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    wellhub: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    totalpass: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    personalExterno: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    faixaPreco: confirmado("premium", "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estilos: confirmado(["funcional", "aulas_coletivas", "cardio", "reservada", "premium"], "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
  },

  {
    id: "24-wellness-alphaville",
    nome: "24 Wellness Alphaville",
    artigoSlug: "24-wellness-alphaville",
    regiao: "centro-industrial-empresarial",
    tipo: "local",
    status: "ativa",
    vinteQuatroHoras: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDomingo: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreSabado: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    fechaDiaUtil: confirmado(23, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDiaUtil: confirmado(5, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estacionamento: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    wellhub: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    totalpass: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    personalExterno: naoConfirmado<boolean>(),
    faixaPreco: confirmado("intermediario", "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estilos: confirmado(["musculacao_completa", "pesos_livres", "maquinas", "aulas_coletivas"], "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
  },
  {
    id: "skyfit-alphaville",
    nome: "SkyFit Alphaville",
    artigoSlug: "skyfit-alphaville",
    regiao: "centro-industrial-empresarial",
    tipo: "local",
    status: "ativa",
    vinteQuatroHoras: naoConfirmado<boolean>(),
    abreDomingo: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreSabado: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    fechaDiaUtil: confirmado(23, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDiaUtil: confirmado(5, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estacionamento: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    wellhub: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    totalpass: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    personalExterno: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    faixaPreco: confirmado("economico", "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estilos: confirmado(["musculacao_completa", "pesos_livres", "maquinas", "cardio", "aulas_coletivas", "funcional"], "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
  },
  {
    id: "studio-mormaii-alphaville",
    nome: "Studio Mormaii Alphaville",
    artigoSlug: "studio-mormaii-alphaville",
    regiao: "centro-comercial",
    tipo: "local",
    status: "ativa",
    vinteQuatroHoras: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDomingo: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreSabado: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    fechaDiaUtil: confirmado(21, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDiaUtil: confirmado(6, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estacionamento: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    wellhub: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    totalpass: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    personalExterno: naoConfirmado<boolean>(),
    faixaPreco: confirmado("intermediario", "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estilos: confirmado(["funcional"], "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
  },
  {
    id: "voi-fit-alphaville",
    nome: "VoiFit Alphaville",
    artigoSlug: "voi-fit-alphaville",
    regiao: "centro-industrial-empresarial",
    tipo: "local",
    status: "ativa",
    vinteQuatroHoras: confirmado(false, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDomingo: naoConfirmado<boolean>(),
    abreSabado: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    fechaDiaUtil: confirmado(22, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    abreDiaUtil: confirmado(6, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estacionamento: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    wellhub: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    totalpass: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    personalExterno: confirmado(true, "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    faixaPreco: confirmado("economico", "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
    estilos: confirmado(["musculacao_completa", "pesos_livres", "maquinas", "aulas_coletivas", "cardio"], "montinho", "verificacao direta do Montinho, que atende alunos na regiao", "2026-08-26"),
  },
  {
    id: "scelta-aldeia-da-serra",
    nome: "Scelta Aldeia da Serra",
    artigoSlug: "scelta-aldeia-da-serra",
    regiao: "aldeia-da-serra",
    tipo: "local",
    status: "encerrada",
    vinteQuatroHoras: naoConfirmado<boolean>(),
    abreDomingo: naoConfirmado<boolean>(),
    abreSabado: naoConfirmado<boolean>(),
    fechaDiaUtil: naoConfirmado<number>(),
    abreDiaUtil: naoConfirmado<number>(),
    estacionamento: naoConfirmado<boolean>(),
    wellhub: naoConfirmado<boolean>(),
    totalpass: naoConfirmado<boolean>(),
    personalExterno: naoConfirmado<boolean>(),
    faixaPreco: naoConfirmado<FaixaPreco>(),
    estilos: naoConfirmado<Estilo[]>(),
  },
];

/**
 * Regiões que têm pelo menos uma academia ativa na base.
 *
 * O questionário só pode oferecer estas. Perguntar "em qual região você passa
 * mais tempo?" e listar uma região onde não temos nenhuma academia ativa é
 * prometer uma resposta que não existe — a pessoa escolhe, e recebe uma lista
 * que ignora justamente o que ela pediu. Quando uma academia daquela região
 * voltar à base, a opção reaparece sozinha.
 */
export function regioesComAcademia(): Regiao[] {
  const vistas = new Set<Regiao>();
  for (const a of ACADEMIAS) if (a.status === "ativa") vistas.add(a.regiao);
  return (Object.keys(REGIAO_LABEL) as Regiao[]).filter((r) => vistas.has(r));
}
